apiVersion: batch/v1
kind: Job
metadata:
  name: "indexed-job"
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: "input"
          image: "docker.io/library/bash"
          command:
            - "bash"
            - "-c"
            - |
              items=(foo bar baz qux xyz)
              echo ${items[$JOB_COMPLETION_INDEX]} > /input/data.txt
          volumeMounts:
            - mountPath: /input
              name: input
      containers:
        - name: "worker"
          image: "docker.io/library/busybox"
          command:
            - "rev"
            - "/input/data.txt"
            # - sleep 20m
          volumeMounts:
            - mountPath: /input
              name: input
      volumes:
        - name: input
          emptyDir: {}
