apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  template:
    metadata:
      name: countdown
    spec:
      containers:
        - name: counter
          image: centos:7
          command:
            - "bin/bash"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
            - "exissssst 125"
      restartPolicy: Never
