apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels: apache
spec:
  replicas: 1
  selector:
    matchLabels: apache
  template:
    metadata:
      labels: apache
    spec:
      containers:
        - name: apache
          image: httpd:2.4.62
          imagePullPolicy: always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
